version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
  db:
    image:  postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
       - "6379:6379"
volumes:
  postgres_data: